[project]
name = "odoo-addons-oca-account-reconcile"
version = "19.0.20260512.0"
dependencies = [
    "odoo-addon-account_reconcile_analytic_tag==19.0.*",
    "odoo-addon-account_reconcile_oca==19.0.*",
    "odoo-addon-account_statement_base==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
